# Generated by Django 4.2.3 on 2023-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Describtion', models.TextField(max_length=100)),
                ('Demo_location', models.TextField(max_length=100)),
            ],
        ),
    ]
